# Pull latest Debian sid
ARG ARCH=
FROM ${ARCH}/debian:sid

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_PRIORITY critical

# Required for https repositories
RUN apt-get update && apt-get install --yes ca-certificates

# Copy relevant repositories and keyrings
# Note: .dummy files used to keep the directory hierarchy in git are
# copied too, see moby/moby#26332
COPY repositories/sid/all/* /etc/apt/sources.list.d/
COPY repositories/sid/arm64/* /etc/apt/sources.list.d/

# Copy apt preferences
COPY preferences/sid/* /etc/apt/preferences.d/

COPY keyrings/all/* /etc/apt/droidian-gpg.d/
COPY keyrings/arm64/* /etc/apt/droidian-gpg.d/

COPY common/apt.conf.d/* /etc/apt/apt.conf.d/
COPY common/preferences.d/* /etc/apt/preferences.d/

# Copy deployer
COPY extra/repo-deploy.sh /usr/local/bin
COPY extra/repo-deps.sh /usr/local/bin

RUN mkdir -p /etc/cutie-build/
COPY extra/cutie-staging.list /etc/cutie-build/

# Add secondary architectures
RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf && dpkg --add-architecture i386

# Update and install
RUN apt-get update && apt-get install -y --allow-downgrades \
 build-essential \
 libncurses-dev \
 bash-completion \
 nano \
 devscripts \
 equivs \
 wget \
 openssh-client \
 rsync \
 ruby-rubygems \
 releng-tools && \
 apt-get dist-upgrade -y --allow-downgrades

# Patch dpkg-perl's Patch.pm to avoid overzealous checks
RUN \
	sed -i \
		"s|error(g_('diff %s modifies file %s through a symlink: %s')|warning(g_('diff %s modifies file %s through a symlink: %s')|" \
		/usr/share/perl5/Dpkg/Source/Patch.pm && \
	echo "libdpkg-perl hold" | dpkg --set-selections

RUN gem install bundler
RUN git clone https://github.com/deb-s3/deb-s3.git /root/deb-s3
RUN cd /root/deb-s3 && bundle add rexml && bundle install && bundle binstubs deb-s3 --path=/usr/bin
